// The Admin de Polo panel, as one lazy chunk (src/app/router.tsx).
export { PlatformLayout, SoonScreen } from './PlatformLayout'
export { OverviewScreen } from './OverviewScreen'
export { TournamentsScreen } from './TournamentsScreen'
export { TournamentDetail } from './TournamentDetail'
export { PeopleScreen } from './PeopleScreen'
export { PersonDetail } from './PersonDetail'
export { CatalogCourses } from './CatalogCourses'
export { CourseDetail } from './CourseDetail'
export { CatalogCrews, CrewDetail } from './CatalogCrews'
